### ISSUE TITLE
Pretrained checkpoint and configuration for reaching the described reward.

### ISSUE THREAD

**Issue by ngoodger** [Miffyli/nle-sample-factory-baseline#1] opened 2022-02-24 10:07 UTC
Thanks so much for sharing this implementation, I think it's a really fantastic implementation.  I would love to try it out and see if I can duplicate the results but I'm running into some issues.

When I run **./train_baseline.sh** I see messages like this:
`Discarding 130 old rollouts, cut by policy lag threshold 10000 (learner 0)`
and the learner doesn't seem to learn anything.  I know this can be fixed by setting the `--max_policy_lag` but the fact it's coming up now implies that either my local setup is different (maybe versions?) or a different configuration was used?  If it's the latter would be possible to share a working configuration?

I tried training from scratch by removing the **train_dir** which increased the **episode_len** without marginal increase to the reward before running into the same "discarding old rollouts" issue.  
`Discarding 130 old rollouts, cut by policy lag threshold 10000 (learner 0)`

Similarly when using the **run.sh** script the reward seems to be a lot less than what is described.  Perhaps the checkpoint doesn't contain a fully trained policy?
```
[2022-02-24 21:05:07,513][06642] Episode finished for agent 0 at 49393 frames. Reward: 34.000, true_reward: 34.000
[2022-02-24 21:05:07,513][06642] Avg episode rewards: #0: 41.200, true rewards: #0: 41.200
[2022-02-24 21:05:07,514][06642] Avg episode reward: 41.200, avg true_reward: 41.200
```

**Comment by Miffyli** [comment] 2022-02-24 13:39
Thanks for reporting this! Not freezing _all_ dependencies bites me yet again (one day I will learn). Try installing `pip install nle==0.7.3` (the version this was built on), and `run.sh` will run much better. `pip install nle==0.8.0` seems to work, too. Below is my complete `pip freeze` for reference (it contains some extra packages).

@heiner I do not see bigger changes in the changelog for v0.8.1, but the performance of training/evaluating drops here + evaluating becomes very slow (agent could be stuck in menus or code could be running slow). Something intended or a potential bug?

```
absl-py==0.13.0
aicrowd-gym==0.0.3
aicrowd-repo2docker==0.11.0
backcall==0.2.0
cachetools==4.2.2
certifi==2021.5.30
charset-normalizer==2.0.1
click==8.0.1
cloudpickle==1.6.0
colorlog==5.0.1
configparser==5.0.2
cycler==0.10.0
Cython==0.29.24
dataclasses==0.6
decorator==4.4.2
docker==4.4.1
docker-pycreds==0.4.0
escapism==1.0.1
faster-fifo==1.2.0
filelock==3.0.12
gitdb==4.0.7
GitPython==3.1.18
google-auth==1.32.1
google-auth-oauthlib==0.4.4
grpcio==1.38.1
gym==0.18.3
idna==3.2
ipython==7.19.0
ipython-genutils==0.2.0
jedi==0.17.2
kiwisolver==1.3.1
llvmlite==0.36.0
loguru==0.5.3
Markdown==3.3.4
matplotlib==3.3.3
minio==7.1.0
msgpack==1.0.2
msgpack-numpy==0.4.7.1
nle==0.8.0
numba==0.53.1
numpy==1.21.0
oauthlib==3.1.1
opencv-python==4.5.3.56
parso==0.7.1
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.2.0
promise==2.3
prompt-toolkit==3.0.8
protobuf==3.17.3
psutil==5.8.0
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybind11==2.6.2
pyglet==1.5.15
Pygments==2.7.3
python-dateutil==2.8.2
python-json-logger==2.0.1
PyYAML==5.4.1
pyzmq==22.2.1
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
sample-factory==1.120.0
scipy==1.7.0
semver==2.13.0
sentry-sdk==1.3.0
shortuuid==1.0.1
six==1.16.0
smmap==4.0.0
subprocess32==3.5.4
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorboardX==2.4
threadpoolctl==2.2.0
timeout-decorator==0.5.0
toml==0.10.2
torch==1.9.0
tqdm==4.53.0
traitlets==5.0.5
typing-extensions==3.7.4.3
urllib3==1.26.6
vizdoom==1.1.9
wandb==0.11.0
wcwidth==0.2.5
websocket-client==0.57.0
Werkzeug==2.0.1
zmq==0.0.0
```

**Comment by heiner** [comment] 2022-02-24 13:55
Hey, thanks for making me aware of this. And my apologies if we broke NLE.

Are you positive it was changes from 0.8.0 to 0.8.1 that caused this? Because as far as I can tell, we changed [two things only](https://github.com/facebookresearch/nle/compare/v0.8.0...v0.8.1):

- How NLE gets nethack settings (no longer uses env variables as they introduce race conditions). I hope this isn't the cause of the issue, and I also can't imagine how it would still run at all but be problematic here.
- We made a breaking change to the action space, adding all SEE* actions. This would impact already-trained models, but I hope it wouldn't change things (much) when you train from scratch?

**Comment by Miffyli** [comment] 2022-02-24 14:29
Ah! That was it, doh :). My eyes checked the first part of the 0.8.1 log but skipped the next, quite important section of "breaking changes". My bad! Sorry for the trouble! All is good (except pretrained models, unsurprisingly).

@ngoodger I also tried training with `nle==0.8.1` and it works as expected, there are no `Discarding 130 old rollouts, cut by policy lag threshold 10000` warnings for me. I am running Ubuntu 20.04LTS with 16 cores and RTX 2080Ti. Check that the trainer process is correctly running (there should be one Python process that is at 100% CPU usage and uses plenty of GPU).

**Comment by heiner** [comment] 2022-02-24 15:08
@Miffyli: Thanks for the update. And thanks for this great baseline btw, we've learned a lot from it. @[condnsdmatters](https://github.com/condnsdmatters) has grabbed a number of ideas from this and put it into a [moolib](https://github.com/facebookresearch/moolib) agent that I hope we can release at some point.

**Comment by ngoodger** [comment] 2022-02-25 12:08
Amazing, thanks both!  Really appreciate the assistance.

Can confirm I was able see much higher reward when using using the run.sh script on `nle==0.7.3`.

Thanks for sharing your configuration and thanks for testing again.  I'm using a  Ubuntu 20:04 in WSL with 8 cores and a 3090 so I guess the learner should be faster but I can't run as many workers.  Anyway I feel a lot more confident now you have tested it recently, so I should be able to to get it work.  Thanks again.

**Comment by Miffyli** [comment] 2022-02-25 15:13
Thank you for the kind comments, they are always welcomed :). Good luck tinkering with NLE!

Closing as resolved.

**Closed as completed by Miffyli** 2022-02-25 15:13 UTC
Labels: question
